version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
      - ./logs:/var/log/app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      COMPOSER_ALLOW_SUPERUSER: "1"
    depends_on:
      - ldap

  ldap:
    image: osixia/openldap:1.5.0
    container_name: symfony_ldap
    environment:
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

volumes:
  ldap_data:
  ldap_config:
