version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
      - ./logs:/var/log/app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      COMPOSER_ALLOW_SUPERUSER: "1"
